services:
  postgres:
    image: postgres:15
    container_name: salao_api
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: salao_db
    ports:
      - "5432:5432"
